### ISSUE TITLE
论坛的主题是什么？由谁来开发维护呢？

### ISSUE THREAD

**Issue by SkipperGuo** [ODotNet/MStack.MainSite#1]
论坛的主题是什么？

**Comment by DukeCheng** [comment]
基点: 围绕微软技术栈展开.
初衷: 记录群里面讨论的重点内容，或者有些重要的讨论转移到网站上来.
网站性质: 初步会是论坛，有发帖，回帖
后续会再根据情况扩充.

**Comment by BeiMeng** [comment]
这个论坛由谁来开发呢？

**Comment by DukeCheng** [comment]
我会来作为第一开发，我个人之前的经验来看，人多就会每人开发，所以核心开发人员不会超过3~5位，其他人可以Fork之后提交代码.
