### ISSUE TITLE
QQ 登录时报错

### ISSUE THREAD

**Issue by garfieldzf8** [ODotNet/MStack.MainSite#20]
获取Dev分支后我在 本地部署站点，然后用QQ登录，报错，是否是本地配置问题？

报错提示：redirect uri is illegal(100010)

**Comment by DukeCheng** [comment]
@garfieldzf8 本地调试无法使用QQ登录，只能修改后提交到Develop分支，在测试环境测试.

**Comment by ylvict** [comment]
QQ的OAuth登录需要回调校验注册时设置的域名，本地无法校验，@garfieldzf8 ，一种方法是直接部署后测试。
如果嫌麻烦可以改本地host文件，将域名直接指向127.0.0.1。

**Comment by DukeCheng** [comment]
@ylvict 是个好方法，通过host文件将www.mstack.club域名指向本地之后， 还需要在本地配置网站及域名

**Comment by DukeCheng** [comment]
@ylvict @garfieldzf8 [OAuth本地调试的方法](https://github.com/ODotNet/MStack.MainSite/wiki/Local-Debug-for-OAtuh-Login)
