### ISSUE TITLE
本地调试时登录失败

### ISSUE THREAD

**Issue by ren8179** [ODotNet/MStack.MainSite#21]
异常详细信息: System.Net.Sockets.SocketException: 这是在主机名解析时通常出现的暂时错误，它意味着本地服务器没有从权威服务器上收到响应。

堆栈跟踪: 

**[SocketException (0x2afa): 这是在主机名解析时通常出现的暂时错误，它意味着本地服务器没有从权威服务器上收到响应。]**
   System.Net.Dns.GetAddrInfo(String name) +6724930
   System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) +106
   System.Net.Dns.GetHostEntry(String hostNameOrAddress) +109
   MySql.Data.Common.MyNetworkStream.CreateStream(MySqlConnectionStringBuilder settings, Boolean unix) +64
   MySql.Data.Common.StreamCreator.GetStream(MySqlConnectionStringBuilder settings) +38
   MySql.Data.MySqlClient.NativeDriver.Open() +55

**[MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.]**
   MySql.Data.MySqlClient.NativeDriver.Open() +151
   MySql.Data.MySqlClient.Driver.Open() +22
   MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings) +239
   MySql.Data.MySqlClient.MySqlPool.GetPooledConnection() +287
   MySql.Data.MySqlClient.MySqlPool.TryToGetDriver() +93
   MySql.Data.MySqlClient.MySqlPool.GetConnection() +65
   MySql.Data.MySqlClient.MySqlConnection.Open() +629
   NHibernate.Connection.DriverConnectionProvider.GetConnection() +112
   NHibernate.Tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.Prepare() +14
   NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.GetReservedWords(Dialect dialect, IConnectionHelper connectionHelper) +71
   NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.Update(ISessionFactory sessionFactory) +78
   NHibernate.Impl.SessionFactoryImpl..ctor(Configuration cfg, IMapping mapping, Settings settings, EventListeners listeners) +700
   NHibernate.Cfg.Configuration.BuildSessionFactory() +104
   MStack.Core.Repositories.NHSessionFactory.Init() in E:\GitProject\MStack.MainSite\src\MStack.Core\Repositories\NHSessionFactory.cs:54
   MStack.Core.Repositories.NHSessionFactory..cctor() in E:\GitProject\MStack.MainSite\src\MStack.Core\Repositories\NHSessionFactory.cs:48

**[TypeInitializationException: “MStack.Core.Repositories.NHSessionFactory”的类型初始值设定项引发异常。]**
   MStack.Core.Repositories.NHSessionFactory.OpenSession() in E:\GitProject\MStack.MainSite\src\MStack.Core\Repositories\NHSessionFactory.cs:34
   MStack.MainSite.WebFramework.Authentication.MyUserStore`1.get_Session() in E:\GitProject\MStack.MainSite\src\MStack.MainSite\WebFramework\Authentication\ApplicationUserRepository.cs:33
   MStack.MainSite.WebFramework.Authentication.MyUserStore`1.FindByNameAsync(String userName) in E:\GitProject\MStack.MainSite\src\MStack.MainSite\WebFramework\Authentication\ApplicationUserRepository.cs:155
   Microsoft.AspNet.Identity.UserManager`2.FindByNameAsync(String userName) +56
   Microsoft.AspNet.Identity.Owin.<PasswordSignInAsync>d__29.MoveNext() +122
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +24
   MStack.MainSite.Controllers.<Login>d__11.MoveNext() in E:\GitProject\MStack.MainSite\src\MStack.MainSite\Controllers\AccountController.cs:83
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +17
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9744373
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by DukeCheng** [comment]
@ren8179 这个是NHIbernate SessionFactory里面报出来的异常，连接远程数据库错误，检查一下你的Connection String , develop的分支我已经更新了connectionString, 你可以参考[这里](https://github.com/ODotNet/MStack.MainSite/wiki/Db-Create-and-Update)更新ConnectionString
