### ISSUE TITLE
论坛界面设计与开发

### ISSUE THREAD

**Issue by DukeCheng** [ODotNet/MStack.MainSite#6]
论坛界面设计参考下面，尽可能全部复制
http://community.miniprofiler.com/

**Comment by garfieldzf8** [comment]
帖子列表页面主要是table布局。根据帖子的数据，动态生成table的tr。 首页显示默认条数，然后下拉时滚动加载。

**Comment by DukeCheng** [comment]
你做出来的时候我发现我犯了一个错误，我们要卡率网站整体的风格, 我把你写的样式的部分放到另外一个文件了, 可以先保留，后面这部分我们还是要尽可能的做参考，自己来写样式，但是照搬的话，对于我们来说貌似不太合适.

**Comment by DukeCheng** [comment]
https://github.com/ODotNet/MStack.MainSite/issues/5 此任务转到#5处理
